import { Move } from "."
import { InBattleStatsKeys } from "../battle/pokemon"
import { TypeEnum  } from "../pokemonType.js"
import { getRandomInt } from "../util/math"

export enum NormalMoveEnum {
  ACUPRESSSURE = 'acupressure',
  AFTER_YOU = 'after you',
  ATTRACT = 'attract',
  ASSIST = 'assist',
  BARRAGE = 'barrage',
  BATON_PASS = 'baton pass',
  BELLY_DRUM = 'belly drum',
  BESTOW = 'bestow',
  BIDE = 'bide',
  BIND = 'bind',
  BLOCK = 'block',
  BODY_SLAM = 'body_slam',
  BOOMBURST = 'boomburst',
  CAMOUFLAGE = 'camouflage',
  CAPTIVATE = 'captivate',
  CHIP_AWAY = 'chip away',
  CELEBRATE = 'celebrate',
  COMET_PUNCH = 'comet_punch',
  CONFIDE = 'confide',
  CONSTRICT = 'constrict',
  CONVERSION_2 = 'conversion 2',
  COPYCAT = 'copycat',
  COURT_CHANGE = 'court change',
  COVET = 'cover',
  CRUSH_CLAW = 'crush claw',
  CRUSH_GRIP = 'crush grip',
  CUT = 'cut',
  DEFENSE_CURL = 'defense curl',
  DISABLE = 'disable',
  DIZZY_PUNCH = 'dizzy punch',
  DOODLE = 'doodle',
  DOUBLE_HIT = 'double hit',
  DOUBLE_SLAP = 'double slap',
  DOUBLE_TEAM = 'double team',
  DOUBLE_EDGE = 'double edge',
  ECHOED_VOICE = 'echoed voice',
  EGG_BOMB = 'egg bomb',
  ENCORE = 'encore',
  ENDEAVOR = 'endeavor',
  ENDURE = 'endure',
  ETRAINMENT = 'entrainment',
  EXPLOSION = 'explosion',
  EXTREME_SPEED = 'extreme speed',
  FACADE = 'facade',
  FAKE_OUT = 'fake out',
  FALSE_SWIPE = 'false swipe',
  FEINT = 'feint',
  FLASH = 'flash',
  FORESIGHT = 'foresight',
  FRUSTRATION = 'frustration',
  FILLET_AWAY = 'fillet_away',
  FLAIL = 'flail',
  FOCUS_ENERGY = 'focus energy',
  FOLLOW_ME = 'follow me',
  FURY_ATTACK = 'fury attack',
  FURY_SWIPES = 'fury swipes',
  GLARE = 'glare',
  GROWL = 'growl',
  GROWTH = 'growth',
  GUILLOTINE = 'guillotine',
  HAPPY_HOUR = 'happy hour',
  HARDEN = 'harden',
  HEAD_CHARGE = 'head charge',
  HEADBUTT = 'headbutt',
  HEAL_BELL = 'heal bell',
  HELPING_HAND = 'helping hand',
  HIDDEN_POWER = 'hidden power',
  HYPER_FANG = 'hyper fang',
  LASER_FOCUS = 'laser focus',
  LOVELY_KISS = 'lovely kiss',
  LUCKY_CHANT = 'lucky chant',
  HOLD_BACK = 'hold back',
  HOLD_HANDS = 'hold_hands',
  HORN_ATTACK = 'horn attack',
  HORN_DRILL = 'horn drill',
  HOWL = 'howl',
  HYPER_BEAM = 'hyper beam',
  HYPER_DRILL = 'hyper drill',
  HYPER_VOICE = 'hyper voice',
  JUDGEMENT = 'jugdement',
  LAST_RESSORT = 'last resort',
  LEER = 'leer',
  LOCK_ON = 'lock-on',
  ME_FIRST = 'me first',
  MEAN_LOOK = 'mean look',
  MEGA_KICK = 'mega kick',
  MEGA_PUNCH = 'mega punch',
  METRONOME = 'metronome',
  MILK_DRINK = 'milk drink',
  MIMIC = 'mimic',
  MIND_READER = 'mind_reader',
  MINIMIZE = 'minimize',
  MORNING_SUN = 'morning sun',
  NOBLE_ROAR = 'noble_roar',
  MULTI_ATTACK = 'multi attack',
  NATURAL_GIFT = 'natural gift',
  NATURE_POWER = 'nature power',
  ODOR_SLEUTH = 'odor sleuth',
  PAIN_SPLIT = 'pain split',
  PAY_DAY = 'pay day',
  PERISH_SONG = 'perish song',
  PLAY_NICE = 'play nice',
  POPULATION_BOMB = 'population bomb',
  POUND = 'pound',
  POWER_SHIFT = 'power shift',
  PRESENT = 'present',
  PROTECT = 'protect',
  PSYCH_UP = 'psych up',
  QUICK_ATTACK = 'quick attack',
  RAGE = 'rage',
  RAGING_BULL = 'raging bull',
  RAPID_SPIN = 'rapid_spin',
  RAZOR_WIND = 'razor_wind',
  RECOVER = 'recover',
  RECYCLE = 'recycle',
  REFLECT_TYPE = 'reflect type',
  REFRESH = 'refresh',
  RELIC_SONG = 'relic song',
  RETALIATE = 'retaliate',
  RETURN = 'return',
  REVELATION_DANCE = 'revelation fance',
  REVIVAL_BLESSING = 'revival blessing',
  ROAR = 'roar',
  ROCK_CLIMB = 'rock_climb',
  ROUND = 'round',
  SAFEGUARD = 'safeguard',
  SCARY_FACE = 'scary face',
  SCRATCH = 'scratch',
  SCREECH = 'screech',
  SECRET_POWER = 'secret power',
  SELF_DESTRUCT = 'self-destruct',
  SHARPEN = 'sharpen',
  SHED_TAIL = 'shed tail',
  SHELL_SMASH = 'shell smash',
  SIMPLE_BEAM = 'simple beam',
  SING = 'sing',
  SKETCH = 'sketch',
  SKULL_BASH = 'skull bash',
  SLACK_OFF = 'slack off',
  SLAM = 'slam',
  SLASH = 'slash',
  SLEEP_TALK = 'sleep talk',
  SMELLING_SALTs = 'smelling salts',
  SMOKESCREEN = 'smokescreen',
  SNORE = 'snore',
  SOFT_BOILED = 'soft boiled',
  SONIC_BOOM = 'sonic boom',
  SPOTLIGHT = 'spotlight',
  SPIKE_CANNON = 'spike cannon',
  SPIT_UP = 'spit up',
  SPLASH = 'splash',
  STOCKPILE = 'stockpile',
  STOMP = 'stomp',
  STRENGHT = 'strenght',
  STRUGGLE = 'struggle',
  STUFF_CHEAKS = 'stuff cheaks',
  SUBSTITUTE = 'substitute',
  SUPER_FANG = 'super fang',
  SUPERSONIC = 'supersonic',
  SWAGGER = 'swagger',
  SWALLOW = 'swallow',
  SWEET_SCENT = 'sweet scent',
  SWIFT = 'swift',
  SWORDS_DANCE = 'swords dance',
  TACKLE = 'tackle',
  TAIl_SLAP = 'tail slap',
  TAIL_WHIP = 'tail whip',
  TAKE_DOWN = 'take down',
  TEARFUL_LOOK = 'tearful look',
  TEATIME = 'teatime',
  TECHNO_BLAST = 'techno_blast',
  TRUMP_CARD = 'trump card',
  TEETER_DANCE = 'teeter dancer',
  TERA_BLAST = 'tera blast',
  TERRAIN_PULSE = 'terrain pulse',
  THRASH = 'thrash',
  TICKLE = 'tickle',
  TIDY_UP = 'tidy up',
  TRANSFORM = 'transform',
  TRI_ATTACK = 'tri attack',
  UPROAR = 'uproar',
  VICE_GRIP = 'vice grip',
  WEATHER_BALL = 'weather ball',
  WHIRLWIND = 'whirlwind',
  WISH = 'wish',
  WORK_UP = 'work up',
  WRAP = 'wrap',
  WRING_OUT = 'wring out',
  YAWN = 'yawn'
}

const { ACUPRESSSURE, AFTER_YOU, ATTRACT, ASSIST, BARRAGE, BATON_PASS, BELLY_DRUM, BESTOW, BIDE, BIND, BLOCK, BODY_SLAM, BOOMBURST, CAMOUFLAGE, CAPTIVATE, CHIP_AWAY, CELEBRATE, COMET_PUNCH, CONFIDE, CONSTRICT, COPYCAT, COURT_CHANGE, COVET, CRUSH_CLAW, CRUSH_GRIP, CUT, DEFENSE_CURL, DISABLE, DIZZY_PUNCH, DOODLE, DOUBLE_HIT, DOUBLE_SLAP, DOUBLE_TEAM, DOUBLE_EDGE, ECHOED_VOICE, EGG_BOMB, ENCORE, ENDEAVOR, ENDURE, ETRAINMENT, EXPLOSION, EXTREME_SPEED, FACADE, FAKE_OUT, FALSE_SWIPE, FEINT, FLASH, FORESIGHT, FRUSTRATION, FILLET_AWAY, FLAIL, FOCUS_ENERGY, FOLLOW_ME, FURY_ATTACK, FURY_SWIPES, GLARE, GROWL, GROWTH, GUILLOTINE, HAPPY_HOUR, HARDEN, HEAD_CHARGE, HEADBUTT, HEAL_BELL, HELPING_HAND, HIDDEN_POWER, HYPER_FANG, LASER_FOCUS, LOVELY_KISS, LUCKY_CHANT, HOLD_BACK, HOLD_HANDS, HORN_ATTACK, HORN_DRILL, HOWL, HYPER_BEAM, HYPER_DRILL, HYPER_VOICE, JUDGEMENT, LAST_RESSORT, LEER, LOCK_ON, ME_FIRST, MEAN_LOOK, MEGA_KICK, MEGA_PUNCH, METRONOME, MILK_DRINK, MIMIC, MIND_READER, MINIMIZE, MORNING_SUN, NOBLE_ROAR, MULTI_ATTACK, NATURAL_GIFT, NATURE_POWER, ODOR_SLEUTH, PAIN_SPLIT, PAY_DAY, PERISH_SONG, PLAY_NICE, POPULATION_BOMB, POUND, POWER_SHIFT, PRESENT,
  PROTECT, PSYCH_UP, QUICK_ATTACK,
  RAGE, RAGING_BULL,
  RAPID_SPIN,
  RAZOR_WIND,
  RECOVER,
  RECYCLE, REFLECT_TYPE,
  REFRESH, RELIC_SONG,
  RETALIATE,
  RETURN, REVELATION_DANCE, REVIVAL_BLESSING,
  ROAR,
  ROCK_CLIMB,
  ROUND,
  SAFEGUARD, SCARY_FACE,
  SCRATCH,
  SCREECH, SECRET_POWER, SELF_DESTRUCT,
  SHARPEN, SHED_TAIL, SHELL_SMASH, SIMPLE_BEAM,
  SING,
  SKETCH, SKULL_BASH, SLACK_OFF,
  SLAM,
  SLASH, SLEEP_TALK, SMELLING_SALTs,
  SMOKESCREEN,
  SNORE, SOFT_BOILED, SONIC_BOOM,
  SPOTLIGHT, SPIKE_CANNON, SPIT_UP, SPLASH,
  STOCKPILE,
  STOMP,
  STRENGHT,
  STRUGGLE, STUFF_CHEAKS,
  SUBSTITUTE, SUPER_FANG,
  SUPERSONIC,
  SWAGGER,
  SWALLOW, SWEET_SCENT,
  SWIFT, SWORDS_DANCE,
  TACKLE, TAIl_SLAP, TAIL_WHIP, TAKE_DOWN, TEARFUL_LOOK,
  TEATIME,
  TECHNO_BLAST, TRUMP_CARD, TEETER_DANCE, TERA_BLAST, TERRAIN_PULSE, THRASH, TICKLE, TIDY_UP, TRANSFORM, TRI_ATTACK,
  UPROAR, VICE_GRIP, WEATHER_BALL, WHIRLWIND,
  WISH, WORK_UP, WRAP, WRING_OUT,
  YAWN } = NormalMoveEnum

  const { NORMAL } = TypeEnum

  export const moveDict: Record<NormalMoveEnum, Move> = {
    [TACKLE]: new Move({
      name: TACKLE,
      type: NORMAL,
      category: 'physical',
      power: 40,
      precision: 100,
      pp: 48,
      attributs: {},
    }),
    [ACUPRESSSURE]: new Move({
      name: ACUPRESSSURE,
      type: NORMAL,
      category: 'status',
      pp: 48,
      attributs: {
        isMissable: false,
        selfTarget: true,
      },
      effect (move) {
        const stats: InBattleStatsKeys[] = ['def', 'spe', 'spAtk', 'spDef', 'atk']
        const key = stats[getRandomInt(0,5)]
        if (move.target) {
          move.target.updateState(key, 2)
        }
      }
    })
  }